version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: votingdb
      MYSQL_USER: votinguser
      MYSQL_PASSWORD: votingpass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    volumes:
      - ./monitoring/.my.cnf:/root/.my.cnf:ro
    environment:
      DATA_SOURCE_NAME: "votinguser:votingpass@tcp(mysql-db:3306)/"
    ports:
      - "9104:9104"
    depends_on:
      - mysql-db
    networks:
      - monitoring-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--collector.netstat'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    pid: "host"
    networks:
      - monitoring-net
    restart: always

  voting-ui:
    build:
      context: ./frontend
    container_name: voting-ui
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql-db
      DB_NAME: votingdb
      DB_USER: votinguser
      DB_PASS: votingpass
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - monitoring-net
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - "--config.file=/etc/alertmanager/config.yml"
    networks:
      - monitoring-net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring-net
    restart: always

  slack-relay:
    build:
      context: ./slack-relay
      dockerfile: dockerfile
    container_name: voting-project-v2-slack-relay
    environment:
      - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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
      - TEAMS_WEBHOOK_URL=https://hclo365.webhook.office.com/webhookb2/407755fd-5bd3-4c5c-bbca-480fe17728d4@189de737-c93a-4f5a-8b68-6f4ca9941912/IncomingWebhook/6f97dee426e749aa95890b8d0c50ca0f/0c39e0b3-a165-4381-90f8-90878f64d741/V2utctz6dvrANPxQU19sBwdjVFla1-wuEAvCoaPp_1fGg1 
    ports:
      - "5000:5000"
    networks:
      - monitoring-net
    restart: unless-stopped



networks:
  monitoring-net:
    driver: bridge
