global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    webhook_configs:
      - url: 'http://slack-relay:5000/slack-relay'
        send_resolved: true
