global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#new-channel'
        send_resolved: true
        text: '{{ range .Alerts }}Alert: {{ .Annotations.summary }}{{ end }}'
