global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#all-testing-alerts'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }}'
        text: >-
          *Alert:* {{ .CommonLabels.alertname }}  
          *Status:* {{ .Status }}  
          *Instance:* {{ .CommonLabels.instance }}  
          *Summary:* {{ .CommonAnnotations.summary }}  
          *Description:* {{ .CommonAnnotations.description }}
